name: cron
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cron.yml'
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: ~

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: trigger
        if: github.event_name == 'schedule'
        env:
          APPVEYOR: ${{ secrets.APPVEYOR }}
          WERCKER: ${{ secrets.WERCKER }}
          CIRCLECI: ${{ secrets.CIRCLECI }}
        run: |
          curl -d 'accountName=triffalin&projectSlug=stupendoRaschietto&branch=main' -H "Authorization: Bearer $APPVEYOR" -X POST https://ci.appveyor.com/api/account/triffalin/builds
          curl -d '{}' -H 'Content-Type: application/json' -X POST "https://circleci.com/api/v1.1/project/github/triffalin/stupendoRaschietto/tree/main?circle-token=$CIRCLECI"

      - name: test
        run: |
          python3 -m unittest tests_runner.py

      - name: update
        if: ${{ github.event_name == 'schedule' && success() }}
        env:
          STUPENDORASCHIETTO_ENV: ${{ secrets.STUPENDORASCHIETTO_ENV }}
        run: |
          python3 update_cached_db.py
